#pragma once
// OLED
#define OLED_DISPLAY_128X64

#define I2C_DRIVER_ENABLE
#define I2C_DRIVER I2CD1
#define I2C1_SCL_PIN GP15
#define I2C1_SDA_PIN GP14

#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2000
